name: photo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bouncing_widget: ^2.0.0
  google_fonts: ^2.2.0
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.18
  provider: ^6.0.2
  image_picker: ^0.8.4+4
  flutter_carousel_slider: ^1.0.8
  google_sign_in: ^5.2.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/jpg/

